apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-test
  labels:
    app: alpaca
    ver: "2"
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpaca
      ver: "2"
      env: test
  template:
    metadata:
      labels:
        app: alpaca
        ver: "2"
        env: test
    spec:
      containers:
      - name: alpaca
        image: gcr.io/kuar-demo/kuard-amd64:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
